-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 22:16:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema apliacacion_web_bdd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apliacacion_web_bdd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apliacacion_web_bdd` DEFAULT CHARACTER SET utf8 ;
USE `apliacacion_web_bdd` ;

-- -----------------------------------------------------
-- Table `apliacacion_web_bdd`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apliacacion_web_bdd`.`Usuarios` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(20) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `apliacacion_web_bdd`.`Tareas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apliacacion_web_bdd`.`Tareas` (
  `id_tarea` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `description` VARCHAR(60) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `fecha_vencimiento` DATETIME NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'no entregada',
  `category` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tarea`, `id_user`),
  INDEX `fk_datosTarea_datosUsuarios_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_datosTarea_datosUsuarios`
    FOREIGN KEY (`id_user`)
    REFERENCES `apliacacion_web_bdd`.`Usuarios` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
